### Questions 1

Create a matrix of 5x5 with random integers, after that swap its first and last rows.

In [129]:
import numpy as np

arr = np.arange(25).reshape(5,5)
print(arr)
temp = np.copy(arr[0])
arr[0] = arr[-1]
arr[-1] = temp
arr

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[20, 21, 22, 23, 24],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4]])

### Question 2

Create a 2D array, remove all rows that contain at least one zero.

In [154]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9],
                [10,0,11]])

def remove_zero(array):
    return np.array([row for row in array if all(element!=0 for element in row)])

remove_zero(arr)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Question 3

Write a NumPy program to find the real and imaginary parts of an array of complex numbers.<br>
Original array [ 1.00000000+0.j 0.70710678+0.70710678j]

In [38]:
arr = np.array( [ 1.00000000+0.j , 0.70710678+0.70710678j])
print("Real Part: ",arr.real)
print("Imaginary Part: ",arr.imag)

Real Part:  [1.         0.70710678]
Imaginary Part:  [0.         0.70710678]


### Question 4

Write a NumPy program to remove the duplicate elements of an array.<br>
Original array:
[10 10 20 20 30 30]


In [158]:
arr = np.array([10,10, 20, 20, 30, 30])

def unique(array):
    uniq = []
    for x in array:
        if x not in uniq:
            uniq.append(x)
    return np.array(uniq)
unique(arr)          

array([10, 20, 30])

### Question 5

Write a NumPy program to create a 3x3x3 array with random values.

In [106]:
arr = np.random.random((3,3,3))
arr

array([[[0.70390879, 0.02708638, 0.50982764],
        [0.73881718, 0.44230611, 0.97161545],
        [0.03704392, 0.64585984, 0.72044767]],

       [[0.77873854, 0.87685931, 0.36911368],
        [0.55073287, 0.90790552, 0.04103522],
        [0.8685538 , 0.94163315, 0.45741308]],

       [[0.71825723, 0.92690142, 0.79200192],
        [0.09319918, 0.13287389, 0.35914048],
        [0.75967126, 0.48505449, 0.3547175 ]]])

### Question 6

Write a NumPy program to create a random vector of size 10 and sort it.
<b>Note:<\b> Do not use builtin sorting function

In [124]:
def selection_sort(n):
    temp = 0
    for i in range(len(n)):
        for j in range(i+1,len(n)):
            if n[i] > n[j]:
                temp = n[i]
                n[i] = n[j]
                n[j] = temp
    return n

# list = [1,4,5,2]
# sort = selection_sort(list)
# print(sort)
                
arr = np.random.randint(1,20,10)
print("Without sort: ",arr)
print("Sorted: ",selection_sort(arr))


Without sort:  [15  2 14 13  8  9 12  5 12  9]
Sorted:  [ 2  5  8  9  9 12 12 13 14 15]


### Question 7

Write a NumPy program to check two random arrays are equal or not.

In [161]:
arr1 = np.random.random(10)
arr2 = np.random.random(10)
np.allclose(arr1,arr2)

False

### Question 8 

Write a NumPy program to sort a given array of shape 2 along the first axis, last axis and on flattened array.<br>

Original array:<br>
[[10 40]<br>
[30 20]]

In [104]:
arr = np.array([[10,40],[30,20]])
print(np.sort(arr,axis=0))
print(np.sort(arr,axis=1))
print(np.sort(arr,axis=None))

[[10 20]
 [30 40]]
[[10 40]
 [20 30]]
[10 20 30 40]


### Question 9

Write a NumPy program to get the floor, ceiling and truncated values of the elements of a numpy array.<br>

Original array:<br>
[-1.6 -1.5 -0.3 0.1 1.4 1.8 2. ]

In [80]:
arr = np.array([-1.6, -1.5, -0.3, 0.1, 1.4, 1.8, 2.])
print(np.floor(arr))
print(np.ceil(arr))
print(np.trunc(arr))

[-2. -2. -1.  0.  1.  1.  2.]
[-1. -1. -0.  1.  2.  2.  2.]
[-1. -1. -0.  0.  1.  1.  2.]


### Questions 10

Write a NumPy program to display all the dates for the month of March, 2017

In [61]:
dates = np.arange('2017-03','2017-04',dtype='datetime64[D]')
dates

array(['2017-03-01', '2017-03-02', '2017-03-03', '2017-03-04',
       '2017-03-05', '2017-03-06', '2017-03-07', '2017-03-08',
       '2017-03-09', '2017-03-10', '2017-03-11', '2017-03-12',
       '2017-03-13', '2017-03-14', '2017-03-15', '2017-03-16',
       '2017-03-17', '2017-03-18', '2017-03-19', '2017-03-20',
       '2017-03-21', '2017-03-22', '2017-03-23', '2017-03-24',
       '2017-03-25', '2017-03-26', '2017-03-27', '2017-03-28',
       '2017-03-29', '2017-03-30', '2017-03-31'], dtype='datetime64[D]')

### Question 11

Write a NumPy program to create 24 python datetime.datetime objects (single object for every hour), and then put it in a numpy array.

In [90]:
import datetime
start = datetime.datetime(2000,1,1)
datetime_arr = np.array([start + datetime.timedelta(hours=i) for i in range(24)])
datetime_arr

array([datetime.datetime(2000, 1, 1, 0, 0),
       datetime.datetime(2000, 1, 1, 1, 0),
       datetime.datetime(2000, 1, 1, 2, 0),
       datetime.datetime(2000, 1, 1, 3, 0),
       datetime.datetime(2000, 1, 1, 4, 0),
       datetime.datetime(2000, 1, 1, 5, 0),
       datetime.datetime(2000, 1, 1, 6, 0),
       datetime.datetime(2000, 1, 1, 7, 0),
       datetime.datetime(2000, 1, 1, 8, 0),
       datetime.datetime(2000, 1, 1, 9, 0),
       datetime.datetime(2000, 1, 1, 10, 0),
       datetime.datetime(2000, 1, 1, 11, 0),
       datetime.datetime(2000, 1, 1, 12, 0),
       datetime.datetime(2000, 1, 1, 13, 0),
       datetime.datetime(2000, 1, 1, 14, 0),
       datetime.datetime(2000, 1, 1, 15, 0),
       datetime.datetime(2000, 1, 1, 16, 0),
       datetime.datetime(2000, 1, 1, 17, 0),
       datetime.datetime(2000, 1, 1, 18, 0),
       datetime.datetime(2000, 1, 1, 19, 0),
       datetime.datetime(2000, 1, 1, 20, 0),
       datetime.datetime(2000, 1, 1, 21, 0),
       datetime.date

### Question 12

Write a NumPy program to concatenate element-wise two arrays of string.<br>
<b>Example <\b>
Array1:<br>
['Python' 'PHP']<br>
Array2:<br>
[' Java' ' C++']<br>
new array:<br>
['Python Java' 'PHP C++']<br>

In [94]:
arr1 = np.array(['Python ','PHP '])
arr2 = np.array(['Java','C++'])
new_arr = np.char.add(arr1,arr2)
new_arr

array(['Python Java', 'PHP C++'], dtype='<U11')